baseURL = "https://newspreadnow.com/"
languageCode = "en-us"
title = "Newspreadnow"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
buildDrafts = false
disableKinds = ["taxonomy","taxonomyTerm"]
[sitemap]
  filename = "sitemap.xml"
  priority = -1
[params]
  author = "Newspreadnow"
