baseURL = 'https://newspreadnow.com/'
title = 'NewspreadNow'
defaultContentLanguage = 'us'
defaultContentLanguageInSubdir = true

[languages]

  [languages.us]
  languageName = 'English (US)'
  weight = 1
  baseURL = 'https://us.newspreadnow.com/'

  [languages.uk]
  languageName = 'English (UK)'
  weight = 2
  baseURL = 'https://uk.newspreadnow.com/'

  [languages.ca]
  languageName = 'English (CA)'
  weight = 3
  baseURL = 'https://ca.newspreadnow.com/'

  [languages.au]
  languageName = 'English (AU)'
  weight = 4
  baseURL = 'https://au.newspreadnow.com/'

  [languages.de]
  languageName = 'Deutsch (DE)'
  weight = 5
  baseURL = 'https://de.newspreadnow.com/'

  [languages.ch]
  languageName = 'Deutsch (CH)'
  weight = 6
  baseURL = 'https://ch.newspreadnow.com/'

  [languages.sg]
  languageName = 'English (SG)'
  weight = 7
  baseURL = 'https://sg.newspreadnow.com/'
  [languages.dk]
  languageName = 'Danish'
  weight = 11
  baseURL = 'https://dk.newspreadnow.com/'

  [languages.fi]
  languageName = 'Finnish'
  weight = 12
  baseURL = 'https://fi.newspreadnow.com/'

  [languages.ae]
  languageName = 'English (UAE)'
  weight = 13
  baseURL = 'https://ae.newspreadnow.com/'

  [languages.nz]
  languageName = 'English (NZ)'
  weight = 14
  baseURL = 'https://nz.newspreadnow.com/'

  [languages.il]
  languageName = 'English (IL)'
  weight = 15
  baseURL = 'https://il.newspreadnow.com/'
  [languages.no]
  languageName = 'Norwegian'
  weight = 8
  baseURL = 'https://no.newspreadnow.com/'

  [languages.se]
  languageName = 'Swedish'
  weight = 9
  baseURL = 'https://se.newspreadnow.com/'

  [languages.nl]
  languageName = 'Dutch'
  weight = 10
  baseURL = 'https://nl.newspreadnow.com/'
